### ISSUE TITLE
unable to define function?

### ISSUE THREAD

**Issue by jilliank12** [MathieuTurcotte/node-backoff#14]
Hello,
I'm having issues with your tutorial -

var call = backoff.call(get, url1+url2, function(err, res) {
                            console.log('=================Num tries : ' + call.getNumRetries());
                            if (err) {
                                console.log('Error: ' + err.message);
                            }
                            else {
                                console.log('Status: ' + res.statusCode);
                            }
                        });
                        call.setStrategy(new backoff.ExponentialStrategy());
                        call.failAfter(10);
                        call.start();

when I try to do this, I get errors like this :

ReferenceError: get is not defined
    at Request._callback (c:\Users\SDS\WebProject\brighticscloudweb\routes\ia.js:389:49)
    at Request.self.callback (c:\Users\SDS\WebProject\brighticscloudweb\node_modules\request\request.js:198:22)
    at Request.emit (events.js:110:17)
    at Request.<anonymous> (c:\Users\SDS\WebProject\brighticscloudweb\node_modules\request\request.js:1057:14)
    at Request.emit (events.js:129:20)
    at IncomingMessage.<anonymous> (c:\Users\SDS\WebProject\brighticscloudweb\node_modules\request\request.js:1003:12)
    at IncomingMessage.emit (events.js:129:20)
    at _stream_readable.js:908:16
    at process._tickCallback (node.js:355:11)

It's unable to define the get function. Any help?

**Comment by jilliank12** [comment]
Sorry, I was confused with function!
Will make a function for get now and you can delete this post too - it wasn't really an issue with this git but didn't know where to ask.
